name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - python-version: 3.6
            django-version: Django==3.0

          - python-version: 3.7
            django-version: Django==3.0

          - python-version: 3.8
            django-version: Django==3.1

          - python-version: 3.9
            django-version: Django==3.1

          - python-version: 3.8
            django-version: Django==4.0

          - python-version: 3.9
            django-version: Django==4.0

          - python-version: "3.10"
            django-version: Django==4.0
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -q ${{ matrix.django-version }}
        python -m pip install .
        python -m pip install coverage==5.3.1
        python -m pip install coveralls==2.2.0

    - name: Run Tests
      run: |
        python manage.py test
#        coverage run --source=jet --omit=*/migrations/*,*/south_migrations/*,*/tests/* manage.py test
#    - name: Coverage report
#      run: |
#        coverage report
#        coveralls